# Generated by Django 4.0.5 on 2023-03-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_approved_by_book_created_by_book_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rent_status',
            field=models.CharField(choices=[('Not_Rent', 'Not Rent'), ('Rent', 'Rent')], default='Not_Rent', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='books'),
        ),
    ]
