# Generated by Django 4.0.5 on 2023-03-07 07:13

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('image', models.ImageField(upload_to='task_reports/', verbose_name='upload')),
            ],
            options={
                'verbose_name': 'Task Report',
                'db_table': 'task_report',
            },
        ),
    ]
