# Generated by Django 4.0.5 on 2023-03-07 07:13

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_report', '0001_initial'),
        ('task_librarian_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLibrarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('author', models.ManyToManyField(to='task_librarian_detail.tasklibrariandetail')),
                ('report', models.ManyToManyField(to='task_report.taskreport')),
            ],
            options={
                'verbose_name': 'Task Librarian',
                'db_table': 'task_librarian',
            },
        ),
    ]
