# Generated by Django 4.0.5 on 2023-03-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_librarian_detail', '0002_tasklibrariandetail_approved_by_and_more'),
        ('task_librarian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklibrarian',
            name='author',
        ),
        migrations.AddField(
            model_name='tasklibrarian',
            name='task_detail',
            field=models.ManyToManyField(to='task_librarian_detail.tasklibrariandetail'),
        ),
    ]
