# Generated by Django 4.0.5 on 2023-03-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_librarian', '0002_remove_tasklibrarian_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklibrarian',
            name='ActiveType',
            field=models.CharField(choices=[('Active', 'Active'), ('Done', 'Done'), ('Not_Active', 'Not Active')], default='Active', max_length=50),
        ),
    ]
